### ISSUE TITLE
Версия в пдф

### ISSUE THREAD

**Issue by GildedHonour** [denisshevchenko/ohaskell#37]
Почему вы просто pdf не закачаете? Зачем гитхаб и столько сложностей из-за того, чтобы скачать книгу? Как ее теперь читать, что надо делать? Как сконвертировать в pdf? Даже просто версию в pdf уже не найти.

**Comment by denisshevchenko** [comment]
Вы правы, просто версию в PDF уже не найти. К сожалению, я так и не научился нормально конвертировать HTML в PDF, получается откровенное уродство.

> Как ее теперь читать

Пока только в онлайне.

**Comment by GildedHonour** [comment]
Но, была же и первая, и вторая версия в pdf, а я ее потерял. У вас разве не осталось?

**Comment by denisshevchenko** [comment]
Они очень старые. С тех пор было дописано несколько глав.

**Comment by GildedHonour** [comment]
После того, как установил  Hakyll и клонировал и распаковал репозиторий, как все это скомпилировать?

**Comment by denisshevchenko** [comment]
В корне репозитория есть скрипт `just_build.sh`. Запускаете его, происходит сборка. После завершения идёте в каталог `_site` - и там увидите `index.html`. Вот и всё.

**Comment by GildedHonour** [comment]
Спасибо.
