### ISSUE TITLE
Пагинация и material design

### ISSUE THREAD

**Issue by everyonesdesign** [denisshevchenko/ohaskell#39]
Новый дизайн книги выдержан в стиле material design от google, однако для стрелок пагинации использован компонент [floating action button](https://www.google.com/design/spec/components/buttons-floating-action-button.html).
Однако сами дизайнеры google считают что ее использование оправдано только для основного позитивного действия на странице.
Я предлагаю использовать дизайнерский фреймворк по назначинию и заменить, например, кнопки пагинации на обычные кнопки.
Что вы думаете по этому поводу?

**Comment by denisshevchenko** [comment]
Да, Юра, ты прав. Я изменил на простую кнопку - и дизайн действительно стал лучше. Большое спасибо за рекомендацию!
